# Generated by Django 5.1.4 on 2025-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarm_tools', '0002_alter_farmer_id_alter_loan_id_alter_maintenance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
