# Generated by Django 5.1.4 on 2025-01-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarm_tools', '0003_tool_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
