# Generated by Django 5.1.4 on 2025-01-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarm_tools', '0004_alter_tool_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='password',
            field=models.CharField(default='123', max_length=50),
        ),
    ]
