# Generated by Django 5.1.4 on 2025-01-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarm_tools', '0005_farmer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
