# Generated by Django 5.1.4 on 2025-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarm_tools', '0006_alter_farmer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
